//! UN/CEFACT units of measure (DM-06, DM-59, Architecture/11 §1.0.1).
//!
//! NGSI-LD encodes a Property's `unitCode` with the UN/CEFACT common codes of UNECE
//! Recommendation 20 (ETSI GS CIM 009). This module is the one code list the platform reads
//! them from: `data/unece-rec20.json`, generated by `tools/units/generate.py` from the pinned
//! Rec 20 revision joined with QUDT, and compiled into a static table by `build.rs`, so a
//! broken list fails the build instead of a request. Nothing here is written by hand.

use serde::Serialize;

/// One unit of the list.
#[derive(Debug, Clone, Copy, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Unit {
    /// The Rec 20 common code, which NGSI-LD puts on the wire as `unitCode` (`GQ`).
    pub code: &'static str,
    /// Rec 20's English name (`microgram per cubic metre`).
    pub name: &'static str,
    /// The symbol a person reads (`µg/m³`); empty for a unit Rec 20 gives none (`piece`).
    pub symbol: &'static str,
    /// Rec 20 marks the code deprecated: still a valid code, not offered to a new model.
    pub deprecated: bool,
    /// QUDT's UCUM code, when QUDT has one.
    pub ucum: Option<&'static str>,
    /// QUDT's unit local name (`MicroGM-PER-M3`), when QUDT maps the code.
    pub qudt: Option<&'static str>,
    /// QUDT's broadest quantity kinds of the unit (`Temperature`, not also `BoilingPoint`).
    pub quantity_kinds: &'static [&'static str],
    /// QUDT's dimension vector (`A0E0L-3I0M1H0T0D0`).
    pub dimension: Option<&'static str>,
    /// Multiplier to the SI unit of the dimension: `si = (value + offset) × factor`. `None`
    /// when QUDT gives none or the unit is logarithmic (decibel): such a unit never converts.
    pub factor: Option<f64>,
    /// Offset added before the factor (273.15 for °C, 459.67 for °F).
    pub offset: f64,
    /// In the municipal set a picker shows first.
    pub frequent: bool,
}

/// Why a unit code was refused.
#[derive(Debug, thiserror::Error, PartialEq, Eq, Clone)]
pub enum UnitError {
    /// Not a Rec 20 common code.
    #[error("`{0}` is not a UN/CEFACT Recommendation 20 unit code")]
    Unknown(String),
    /// The unit has no linear factor to its SI unit.
    #[error("`{0}` cannot be converted: the code list gives it no conversion factor")]
    NotConvertible(String),
    /// The two units measure different things.
    #[error("`{from}` and `{to}` measure different quantities and do not convert into each other")]
    DifferentQuantities {
        /// Code converted from.
        from: String,
        /// Code converted to.
        to: String,
    },
}

static UNITS: &[Unit] = include!(concat!(env!("OUT_DIR"), "/units_table.rs"));

/// Every unit of the list, sorted by code.
pub fn all() -> &'static [Unit] {
    UNITS
}

/// The unit of a Rec 20 code; codes are case-sensitive, as on the wire.
pub fn lookup(code: &str) -> Option<&'static Unit> {
    UNITS
        .binary_search_by(|unit| unit.code.cmp(code))
        .ok()
        .map(|index| &UNITS[index])
}

/// The unit of a code, or an error that names the code for the person who wrote it.
pub fn validate(code: &str) -> Result<&'static Unit, UnitError> {
    lookup(code).ok_or_else(|| UnitError::Unknown(code.to_owned()))
}

/// Converts `value` from one unit to another through their SI unit (DM-06).
///
/// The two must share QUDT's dimension vector and at least one quantity kind: a percent and a
/// minute of arc are both dimensionless, and still not one thing in two units. The same code
/// on both sides returns the value unchanged, convertible or not.
pub fn convert(value: f64, from: &str, to: &str) -> Result<f64, UnitError> {
    let source = validate(from)?;
    let target = validate(to)?;
    if source.code == target.code {
        return Ok(value);
    }
    let factor_of = |unit: &Unit| {
        unit.factor
            .ok_or_else(|| UnitError::NotConvertible(unit.code.to_owned()))
    };
    let (from_factor, to_factor) = (factor_of(source)?, factor_of(target)?);
    let same_kind = source
        .quantity_kinds
        .iter()
        .any(|kind| target.quantity_kinds.contains(kind));
    if source.dimension != target.dimension || !same_kind {
        return Err(UnitError::DifferentQuantities {
            from: source.code.to_owned(),
            to: target.code.to_owned(),
        });
    }
    let si = (value + source.offset) * from_factor;
    Ok(si / to_factor - target.offset)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn close(a: f64, b: f64) -> bool {
        (a - b).abs() <= 1e-9 * b.abs().max(1.0)
    }

    #[test]
    fn a_known_code_is_found_and_an_unknown_one_named() {
        let unit = validate("GQ").expect("GQ is Rec 20");
        assert_eq!(unit.name, "microgram per cubic metre");
        assert_eq!(unit.symbol, "µg/m³");
        assert_eq!(unit.qudt, Some("MicroGM-PER-M3"));
        assert_eq!(
            validate("ug/m3"),
            Err(UnitError::Unknown("ug/m3".to_owned()))
        );
        assert_eq!(lookup("gq"), None, "codes are case-sensitive");
        assert_eq!(lookup(""), None);
    }

    #[test]
    fn hectopascal_is_a97_and_hpa_is_alcohol() {
        assert_eq!(lookup("A97").map(|u| u.name), Some("hectopascal"));
        assert_eq!(
            lookup("HPA").map(|u| u.name),
            Some("hectolitre of pure alcohol")
        );
    }

    #[test]
    fn concentrations_temperatures_and_speeds_convert() {
        assert!(close(convert(0.035, "GP", "GQ").unwrap(), 35.0));
        assert!(close(convert(212.0, "FAH", "CEL").unwrap(), 100.0));
        assert!(close(convert(-40.0, "CEL", "FAH").unwrap(), -40.0));
        assert!(close(convert(0.0, "CEL", "KEL").unwrap(), 273.15));
        assert!(close(convert(36.0, "KMH", "MTS").unwrap(), 10.0));
        assert!(close(convert(1.0, "KWH", "JOU").unwrap(), 3.6e6));
    }

    #[test]
    fn different_quantities_and_factorless_units_are_refused() {
        assert_eq!(
            convert(1.0, "CEL", "GQ"),
            Err(UnitError::DifferentQuantities {
                from: "CEL".into(),
                to: "GQ".into()
            })
        );
        assert_eq!(
            convert(1.0, "D61", "P1"),
            Err(UnitError::DifferentQuantities {
                from: "D61".into(),
                to: "P1".into()
            }),
            "a minute of arc is not a percent though both are dimensionless"
        );
        assert_eq!(
            convert(3.0, "2N", "P1"),
            Err(UnitError::NotConvertible("2N".into()))
        );
        assert_eq!(
            convert(3.0, "XYZ", "P1"),
            Err(UnitError::Unknown("XYZ".into()))
        );
        assert_eq!(convert(3.0, "H87", "H87"), Ok(3.0));
    }

    #[test]
    fn every_copy_of_the_list_is_the_generated_source() {
        let source = include_bytes!("../data/unece-rec20.json");
        let copies: [(&str, &[u8]); 1] = [(
            "tools/model-tools/models/unece-rec20.json",
            include_bytes!("../../../tools/model-tools/models/unece-rec20.json"),
        )];
        for (path, copy) in copies {
            assert!(
                copy == source,
                "{path} differs from crates/jc-core/data/unece-rec20.json: run tools/units/generate.py"
            );
        }
    }

    #[test]
    fn the_list_is_sorted_unique_and_carries_the_frequent_set() {
        assert!(all().windows(2).all(|pair| pair[0].code < pair[1].code));
        assert!(all().len() > 1500, "the whole recommendation, not a subset");
        let frequent: Vec<_> = all()
            .iter()
            .filter(|u| u.frequent)
            .map(|u| u.code)
            .collect();
        for code in ["GQ", "CEL", "P1", "KMH", "KWH", "A97", "C62"] {
            assert!(frequent.contains(&code), "{code} is frequent");
        }
        assert!(all().iter().all(|u| u.factor.is_none_or(|f| f > 0.0)));
    }
}
